version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.6.0-browsers

    steps:
      - checkout

      - run: npm install

      - run:
          name: Download Selenium
          command: sudo npm install selenium-standalone@latest -g
      - run:
          name: Start Selenium
          command: selenium-standalone install && selenium-standalone start
          background: true

      - run: npm test

      - store_artifacts:
          path: html-report/
          destination: /html-reporter
