version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6.0
      - image: circleci/node:jessie-browsers

    steps:
      - checkout

      - run: npm install

      - run:
          name: Download Selenium
          command: sudo npm install selenium-standalone@latest -g
      - run:
          name: Start Selenium
          command: selenium-standalone install && selenium-standalone start
          background: true

      - run: npm test
