version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run: npm install

      - run: npm install selenium-standalone@latest -g
      - run: selenium-standalone install && selenium-standalone start > selenium.txt 2>&1 </dev/null &

      - run: npm test
